language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: CpCabpM+KxtSijOAc5vc0g6bHBLURWh3oLp7HiyRGejF4OrrcCmrCqYk1vPkf1rRFttADzj2A5g9PQpJHzQu1/8HPnbCPwy+RFo1iiv700VNq0YBtzjJi3PdpZKqjC1UMdndxyZCN4UNRQuAnq+b5a9CXM9lbjwK2KKpSNcmFKrMpjECtVf4+h1GB/d4G1XKwIxY57HDC73Zm3oOiWjeBm7b0ilP3H8uvon+4NonTtXdvPmGKK59VVMLpCJtVG14q7px0B5bIRGpxZiDQE4ShThr4Rv1Iy5rLWKsjOwpcjCjs7AQcMSXdLOg0ZZB/U62KEZweRoez6buRZFRdMbtW3IPDzQ36mTVLeAHnBAv+pvvMBfS8b+igHNC8RMDYIXcbi7noXlYn+7s/9l/TzgrOiiMjHwarU/G/M9Xx1zewxWGiO6Vs8TuhBcRFKIFcVMKnTbyMi2So/DX6i7WTSNVOTLGuEeYq57D/vhd3OCZTzEzUyHWtWV9XHS09hBGSK2vl1SuZHuu9MPZD37F5A2p8xpPljkfCxFMWFYGiWhpcz0lj/lOfq4YVyVeuIizIKNjIj3Mv0kw1iGx84KjX6VRXcLmOLug23HiossWfqxrbocOPDI1BaYCigjq9DCYBGbTRgCaetjm2/6RzgRYbvzyPTwhbR7a26AIZPGMaeqynhQ=
  app: warm-citadel-64777
  on:
    repo: EHale64/viewing_party
    branch: main
  skip_cleanup: 'true'
  run: rails db:migrate
env:
  global:
    secure: PCeeLahdBW/DEKWFnbLmQPkoFNQhd9jlwWRfysqUisvFFu/3ozAainqxCNU8gGRXmbs4pAZw3m9XNRspsq7Ebtp0zqEMX+mqh8/PeJW3A1Pc5BkUInNDXErSBd2b3rZnpNQLwG2zgnFuuopBbFPBnCrroT2faDtPXjzJ6QQgK0EWDljK7FRJ8ZAh0skwG4alCLhi1yKn/YkL3uM/7ZS9pXcDYvUJeYBxlfrDTXOETNpP9fJt3IANQGW98qe5jLZF3ebym6qwxVjO0163Xrk23EQa5yWIkXXhSDafLmUisyZjSYjqQWDtmRVa/Sin8L6o3vbxH7hu8Dy9CFidysy1XWNf361F1mQEC5Qn99uqP6UZwRnSothDWUbh3FyKtiPsVNhz2FfjelkUiqKiz/AdLxIQIjmDBuQfzs5GjwnES6uZAfLvGr6FbULQo+WY++URZumrEWFpRPxAMKhLUspQFB9aloCMxWnKkNUhMOHqoiEWjTBYiIlQl2qIqqfIa8tGGIUws7z0o1SGd4NxgxOAlwIZV4OAIsfyFngSJescJrc0kvsks/4PftVT4tTIfNKcp+T3u9yqeKxK7/wfxMViRmEW64hEq1XfipW/iS9KHJzNhGDkhAZsqC94KgFJiFVTZGKEsa+OCHCI2TNZ6N1ET5zZuWLo4N1sT16WSlkGaoA=
