language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 
  app: 
  run: rails db:migrate
env:
  global:
    secure: PCeeLahdBW/DEKWFnbLmQPkoFNQhd9jlwWRfysqUisvFFu/3ozAainqxCNU8gGRXmbs4pAZw3m9XNRspsq7Ebtp0zqEMX+mqh8/PeJW3A1Pc5BkUInNDXErSBd2b3rZnpNQLwG2zgnFuuopBbFPBnCrroT2faDtPXjzJ6QQgK0EWDljK7FRJ8ZAh0skwG4alCLhi1yKn/YkL3uM/7ZS9pXcDYvUJeYBxlfrDTXOETNpP9fJt3IANQGW98qe5jLZF3ebym6qwxVjO0163Xrk23EQa5yWIkXXhSDafLmUisyZjSYjqQWDtmRVa/Sin8L6o3vbxH7hu8Dy9CFidysy1XWNf361F1mQEC5Qn99uqP6UZwRnSothDWUbh3FyKtiPsVNhz2FfjelkUiqKiz/AdLxIQIjmDBuQfzs5GjwnES6uZAfLvGr6FbULQo+WY++URZumrEWFpRPxAMKhLUspQFB9aloCMxWnKkNUhMOHqoiEWjTBYiIlQl2qIqqfIa8tGGIUws7z0o1SGd4NxgxOAlwIZV4OAIsfyFngSJescJrc0kvsks/4PftVT4tTIfNKcp+T3u9yqeKxK7/wfxMViRmEW64hEq1XfipW/iS9KHJzNhGDkhAZsqC94KgFJiFVTZGKEsa+OCHCI2TNZ6N1ET5zZuWLo4N1sT16WSlkGaoA=
